import { FormEvent, useEffect, useState } from 'react';
import { Activity, Database, Gauge, Plus, ShieldCheck, UserCog } from 'lucide-react';
import { api } from './api';
import type { Job } from './types';
import './phase6.css';

type User={id:number;email:string;role:string};
type Runtime={environment:string;database:string;max_upload_mb:number;ai_calls_per_minute:number;ai_monthly_token_budget:number};
type Usage={requests:number;successful:number;fallbacks:number;total_tokens:number;average_duration_ms:number};

export default function Admin({job,close}:{job?:Job;close:()=>void}){
  const [users,setUsers]=useState<User[]>([]);const [assigned,setAssigned]=useState<number[]>([]);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [runtime,setRuntime]=useState<Runtime>();const [usage,setUsage]=useState<Usage>();
  const load=async()=>{try{const [loadedUsers,loadedRuntime,loadedUsage]=await Promise.all([api('/admin/users'),api('/admin/runtime'),api('/admin/ai/usage')]);setUsers(loadedUsers);setRuntime(loadedRuntime);setUsage(loadedUsage);if(job)setAssigned((await api('/admin/jobs/'+job.id+'/assignments')).user_ids)}catch(e){setError((e as Error).message)}};
  useEffect(()=>{load()},[job?.id]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));try{await api('/admin/users',{method:'POST',body:JSON.stringify(payload)});e.currentTarget.reset();setNotice('User created');await load()}catch(err){setError((err as Error).message)}}
  async function saveAssignments(){if(!job)return;await api(`/admin/jobs/${job.id}/assignments`,{method:'PUT',body:JSON.stringify({user_ids:assigned})});setNotice(`Assignments saved for ${job.title}`)}
  return <div className="modal wide"><section className="modal-panel admin-console"><div className="modal-title"><div><p className="eyebrow">Administration</p><h2>User and access management</h2></div><button className="ghost" onClick={close}>Close</button></div>{runtime&&usage&&<><div className="ops-grid"><article><Database/><span>Database</span><strong>{runtime.database}</strong><small>{runtime.environment}</small></article><article><Activity/><span>AI requests</span><strong>{usage.requests}</strong><small>{usage.successful} successful · {usage.fallbacks} fallback</small></article><article><Gauge/><span>AI tokens</span><strong>{usage.total_tokens.toLocaleString()}</strong><small>{usage.average_duration_ms} ms average</small></article><article><ShieldCheck/><span>Application limit</span><strong>{runtime.ai_calls_per_minute}/min</strong><small>{runtime.ai_monthly_token_budget||"No"} token budget</small></article></div><p className="ops-note">Operational metrics exclude API keys and prompt content.</p></>}{error?<div className="error access-error"><ShieldCheck/>{error}<small>Sign in as admin@recruitai.local to manage users and assignments.</small></div>:<><div className="admin-grid"><section><h3>Create user</h3><form onSubmit={create}><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength={8} required/></label><label>Role<select name="role"><option value="recruiter">Recruiter</option><option value="hiring_manager">Hiring manager</option><option value="admin">Administrator</option></select></label><button><Plus/> Create user</button></form></section><section><h3>Active users</h3><div className="user-list">{users.map(user=><article key={user.id}><UserCog/><div><strong>{user.email}</strong><span>{user.role.replace('_',' ')}</span></div></article>)}</div></section></div>{job&&<section className="assignments"><h3>Assign “{job.title}”</h3><p>Assigned recruiters and hiring managers can access this role. Administrators always retain access.</p>{users.filter(u=>u.role!=='admin').map(user=><label key={user.id}><input type="checkbox" checked={assigned.includes(user.id)} onChange={e=>setAssigned(ids=>e.target.checked?[...ids,user.id]:ids.filter(id=>id!==user.id))}/><span>{user.email}</span><em>{user.role.replace('_',' ')}</em></label>)}<button onClick={saveAssignments}>Save assignments</button></section>}{notice&&<div className="notice">{notice}</div>}</>}</section></div>
}

